# GENERAL SETTING
experiments_dir: 'experiments'

target_uuid: '98728221'
model_uuid: '2504141151'

model_type: 'XL'
size: 1024
device: 'cuda'

# GENERATE

# target_prompt: 'A handsome teenager wearing shorts and canvas shoes, digital painting'
# target_dir: 'teenager_wearing_shorts_and_canvas_shoes'
# add_target_prompt: 'contrast solid background'
# target_neg_prompt: ''
# base: 'teenager'
# add_prompts: ['a city as background',
#    'the Effel Tower as a background',
#    'the Statue of liberty as a background',
#    'eating a burger',
#    'wearing sunglasses']
# neg_prompts: ['', '', '', '', '']
# file_names: ['a_city_as_background',
#    'the_effel_tower_as_a_background',
#    'the_statue_of_liberty_as_a_background',
#    'eating_a_burger',
#    'wearing_sunglasses']

# target_prompt: 'A young woman with long wavy hair wairing sundress, photo realistic' # CHANGE HERE, MAKE SURE IT CONTAINS THE BASE WORD
# target_dir: 'young_woman_with_long_wavy_hair'
# add_target_prompt: 'contrast solid background'
# target_neg_prompt: ''
# base: 'woman' # CHANGE HERE
# add_prompts: ['standing in wildflowers',
#    'walking on sunset beach',
#    'sitting at cafe',
#    'leaning on a fence']
# neg_prompts: ['', '', '', '']
# file_names: ['standing_in_wildflowers',
#    'walking_on_sunset_beach',
#    'sitting_at_cafe',
#    'leaning_on_a_fence']

target_prompt: 'A rugger adventurer with tousled hair, comic book stile' # CHANGE HERE, MAKE SURE IT CONTAINS THE BASE WORD
target_dir: 'adventurer_with_tousled_hair_comic_book'
add_target_prompt: ''
target_neg_prompt: ''
base: 'adventurer'# CHANGE HERE
add_prompts: ['a city as background',
   'the Effel Tower as a background',
   'the Statue of liberty as a background',
   'eating a burger',
   'wearing sunglasses']
neg_prompts: ['', '', '', '', '']
file_names: ['a_city_as_background',
   'the_effel_tower_as_a_background',
   'the_statue_of_liberty_as_a_background',
   'eating_a_burger',
   'wearing_sunglasses']

steps: 30
guidance_scale: 7.5
g_seed: 5643
gen_base: 10 # Generate auxiliary images

# TUNE
concept_type: 'character'  # CHANGE HERE, choose from 'character' 'object' 'style'
t_seed: 777
lr: 0.0001
neg_num: 3 # Auxiliary images used in a batch
lambda1: 0.5
lambda2: 0.2
batch_size: 1 # Fixed
epochs: 1
save_steps: 10
checkpointing_steps: 500
resume_from_checkpoint: None  # True or None
xt_to_use: -1

# My parameters
use_mask : True
mask_power: 1 # 0+, 0 - no effect, 10000 - extreeme 
mask_alpha: 0.5 # (1 - alpha) * 1 + alpha * mask, from 0 to 1, 0 - no effect
use_zone: False
zone_alpha: 1 # (1 - alpha) * 1 + alpha * mask

# env config
use_xformers: True
allow_tf32: True


# INFERENCE

seed: 32018
inference_steps: 30
select_steps: [1,20]  # appplying cluster guidance to these steps
only_step: [20, 40, 80, 100]  # type in a specific step (Recommended) or set to 'best'

v: 0.8 # semantic interpolation scales
eta_1: 7.5  # target attraction scale
eta_2: 0  # auxiliary exclusion scale (set to 0 will avoid increasing inference time)

xt_position: -1
